ONSdigital/dp-cantabular-filter-flex-api

- api/filters.go
- datastore/mongodb/filters.go
- features/filters.authorized.feature
- features/filters.dimensions.feature
- features/filters.feature
- model/filter.go
Removed asserting filterID and instanceID as UUID as when saving to mongo we need to use string values to keep consistent with existing code (MongoDB will save UUIDs as binary rather using the stringified value)
Check changes make sense, tests pass
Anyone
> use string value for IDs

- api/contract.go
- api/filters.go
- api/interface.go
- api/pagination.go
- api/pagination_test.go
- config/config.go
- datastore/mongodb/filters.go
- features/create_filter.authorized.feature
- features/create_filter.feature
- features/filters.dimensions.feature
- features/steps/steps.go
- service/interface.go
- service/mock/datastore.go
- swagger.yaml
Updates the dimensions endpoint to conform to the ONS pagination standards.
Since dimensions are nested inside filters, we used `unwind` and `facet` to pull out the relevant info. Unlike `findOne`, aggregates always seem to return a list of results, and therefore don't seem to provide an easy way for us to determine if the top-level filter is missing. We've added a flag which gets set in the event that any matches are returned, but another alternative would be running a separate `Count()` query first.
(First time working with Mongo, so any alternatives/suggestions welcome.)
This is effectively a breaking change, since it renames `dimensions` to `items`. However, the client is [already set up](https://github.com/ONSdigital/dp-api-clients-go/blob/2b9ec3cde38ebe3b0e37971bff49cf154969f566/filt …
> Add pagination to dimensions in Filter Flex API (Ticket #5559)

- api/api.go
- features/filters.dimension.authorised.feature
We should enable the private endpoint for POST '/filter/{id}/dimensions'
Resolves: [5568](https://trello.com/c/6L3QBhtd/5568-create-post-filters-id-dimensions-name-endpoint)
* Runs tests 
any developer
> Enable POST '/filter/{id}/dimensions' private endpoint

- api/api.go
- api/contract.go
- api/filters.go
- api/mock/create_filter-outputs.request.develop.json
- features/put_filter.feature
- model/filter.go
Added skeleton PUT endpoint for filters/{id}. Currently the endpoint will just return a predefined response
1. The response matches the swagger spec of response
2. api/mock/create_filter-outputs.request.develop.json this is not related to this commit, but is part of testing the filter outputs in develop
Anyone
> Added support for PUT filters/{id}

- api/contract.go
- api/filters.go
- features/create_filter.authorized.feature
- features/create_filter.feature
- model/filter.go
* Update the POST /filters response model
Significant changes:
* include a `population_type` based on [this PR](https://github.com/ONSdigital/dp-cantabular-filter-flex-api/pull/31/files#diff-8b1949772e223a1da6a2049ada2733fa506410975b241cf86cf44c7a8665bc62R531)
* Removal of dimensions list and replace that with an URL to get the
filter dimensions instead
* remove `published` and `type`
* Create a new Filter Output response
This will be used when we implement a new `PUT /filter-output` endpoint
run tests and review swagger.json
any developer
> Update filter response model

- config/config.go
- service/kafka.go
In the work previously, the configuration definition
was mistakenly changed. This changes it back to
the cantabular-csv-exporter-service definition.
run `make test-component` and `make test`
please review the shape of the config struct and the 
`kafka` logic, and confirm that they are right for the service. 
Team B
> fix: Kafka config definition changed back

- api/api.go
- api/contract.go
- api/filters.go
- api/interface.go
- datastore/mongodb/filter_dimensions.go
- features/filters.dimension.authorised.feature
- features/filters.dimensions.feature
- service/interface.go
- service/mock/datastore.go
- swagger.yaml
Adds an endpoint to get a single dimension: `GET /filters/:filter/dimensions/:dimension`
We include the `is_area_type` flag so the frontend can switch on it. Going to revisit this later, but adding in now to fix the frontend journey which uses it.
Resolves: [5570](https://trello.com/c/8xCrDyR1)
Check the endpoint matches the schema and ticket requirements.
Anyone.
> Add GET filter dimension endpoint (#5570)

- api/events.go
- api/filters.go
There is no need to pass a pointer/reference.
A copy will suffice and is more efficient for such a small struct.
This PR
Anyone.
> Stop passing a reference to event.ExportStart

- api/contract.go
- api/filters.go
- datastore/mongodb/filter_dimensions.go
- datastore/mongodb/interface.go
- features/create_filter.authorized.feature
- features/create_filter.feature
- features/filters.dimension.authorised.feature
- features/filters.dimensions.feature
- features/put_filters_dimensions.feature
- features/steps/steps.go
- model/filter.go
- swagger.yaml
Now stores two additional fields on a filter dimensions: ID and label.
Previously we assumed that the `name` field on a filter was sufficient, since it would contain the selection for a dimension (e.g. `name: "city"`). Our new understanding is that the underlying name should remain unchanged (e.g. consistently `name: "geography"`), which means that we also need to store the currently selected choice (`id`). The label is included as a convenience for the frontend and any other consumers.
This is one step towards [5664](https://trello.com/c/3TbBPTvY), and will enable the frontend to query for/update a specific filter dimension using a consistent machine-readable name (once the import process has also been updated).
Ensure the change makes sense, both conceptually/schema wise and in …
> Add ID/Label to stored filters (#5664)

- go.mod
- go.sum
Trying to understand why the csv-exporter is not able to read the
messages correctly. This will bring the dependency versions to the same
of the csv-exporter service.
Relates to: https://github.com/ONSdigital/dp-cantabular-csv-exporter/pull/65
Resolves: [5660](https://trello.com/c/MoJSwBOg/5660-downloads-no-longer-generating-for-cantabulartable-type)
Simple dependencies update.
Anyone
> Update Kafka and Sarama dependencies

- features/put_filter_outputs.feature
- model/filter.go
Updated validation for updating filter outputs to allow 'public' and 'private' fields to be updated individually.
Anyone
> allow public or private to be empty when updating filter ouput downloads

- go.mod
- go.sum
Upgrade dp-api-clients go to move to Cantabular v10
Anyone
> bump dp-api-clients-go version

- api/filter_dimension_options.go
- api/filter_dimensions.go
- api/filters.go
Moved filter/{id}/dimensions based handlers to their own file filter_dimensions.go, created blank filter_dimension_options.go in preperation for upcoming PRs.
This to save extra clutter in the forthcoming PRs with actual changes.
Also refactored usage of `isValidDatasetDImension` as it was misleading and obscuring the codepath while not saving much/any lines of code.
No functionality should have changed, no tests updated.
Check changes make sense, tests still pass
Anyone
> break down api/filters.go separate file for dimensions

- api/filters.go
- api/filters_test.go
- features/create_filter.authorized.feature
- model/filter.go
[5772 - Add FilterByParent to the Dimension model](https://github.com/ONSdigital/dp-cantabular-filter-flex-api/commit/15b373510e1b22f339ad8dcbb2997f9d435e513f)
Also a small change to `validateDimensionOptions` to check if the `FilterByParent` is preseent.
If it is, use value instead of Dimension.ID for filter.Variable
Also I am syncing  `master` with `develop` 
Sense check it and ensure tests are green
Any ONS developer
> 5772 - Add FilterByParent to the Dimension model

- go.mod
- go.sum
**Update dp-api-client-go to v2.159.1**
When we send a query to dp-cantabular-api-ext to retrieve a list of
categories for a variable, we are also requesting the values
(i.e. the observation numbers) which is not needed here.
It was triggering the SDC rules applied on the population-type.
**Resolves:** [5782](https://trello.com/c/BgynyRgB/5785-update-cantabular-query-that-retrieves-dimension-options)
**Related:** https://github.com/ONSdigital/dp-api-clients-go/pull/299
Sense check and ensure tests are :green_circle: 
Any ONS developer
> 5785 - Do not request 'values' when querying Dimension Options

- go.mod
- go.sum
Currently when our services do a healthcheck against `cantabular-api-ext` an empty query is sent to check the connectivity which is throwing errors in the logs and making it difficult to debug the extended api.
The error that appears on the logs is the following:
```
t=2022-09-21T16:27:56Z ns=api-ext lvl=info ev=graphql query={} op= vars=
t=2022-09-21T16:27:56Z ns=api-ext lvl=info ev=message msg="GraphQL error: Syntax Error GraphQL request (1:1) Unexpected empty IN {}\n\n1: {}\n   ^\n"
t=2022-09-21T16:27:56Z ns=api-ext lvl=info ev=http port=8492 url="/graphql?query={}" method=GET httpStatus=200 contentType=application/json remoteAddr=172.20.0.34 authUser= nBytes=150
```
Going forward the response on the logs should be:
```
t=2022-09-21T17:06:33Z ns=api-ext lvl=info ev=graphql …
```
> 5862 Update Cantabular API Ext Healthcheck query

- datastore/mongodb/filter_outputs.go
Comment out the locking when updating filter outputs. 
This is to experiment whether the 300 concurrent user test can pass. 
Tests were left as is, because it is unclear whether this locking will stay in the future.
run `make test` and `make test-component` to see no changes 
inspect commented code
team b
> patch: remove filter output locking

- api/api.go
- config/config.go
Endpoint /filter-outputs/{id} is now exposed as public endpoint as this is used in web filter flex journey to generate the downloads. 
All tests are :green_circle:
Anyone
> Added put filter outputs as public endpoint

- api/contract.go
- features/filter_dimension.authorised.feature
- features/filter_dimension.feature
- features/multivariate_add_dimension.authorized.feature
- features/multivariate_put_dimension.authorized.feature
- features/put_filters_dimensions.feature
Ticket: https://trello.com/c/2znwf21t/5994-dp-api-clients-go-suggested-category-flag-is-not-population-with-information
Fixed typo default_categorisation which was the issue with missing info when called via api client
All test are :green_circle: 
Anyone
> Fixed issue with missing default_categorisation

- go.mod
- go.sum
Upgrade `dp-api-clients-go` version to `v2.228.0`
Confirm we are using `v2.228.0` of `dp-api-clients-go`
Anyone
> upgrade dp-api-clients-go to 2.228.0

- api/validation.go
Fix for QualityStatementText and QualityStatementURL not showing in filtered dimension response
Should be `node.QualityStatementText` and `node.QualitySummaryURL` instead of `dim`, as `dim` is just the dimensions that we're passing into that function, rather than what's being returned from the `getCantabularDimension` function
Changes make sense, tests pass
Anyone
> fix for quality statement/url

- api/dataset.go
- go.mod
- go.sum
Add temporary debugging code to dump http headers on specific requests
This will enable us to add a url parameter on specific requests and get a dump of the request's internal http request headers in the logs. For safety reasons, only the values of configured headers will be dumped out in order to prevent logging of sensitive values, eg. auth tokens. Also this functionality is only enabled when the debug key is set so causes no performance hit if unintentionally deployed to prod. 
This code is only intended to be deployed as far as staging so it can be tested with CloudFlare. 
To use, the env vars will be configured in vault…
- `ROUTER_DEBUG_KEY` = some value only know to us to stop anyone public using it (debugging disabled if blank)
- `ROUTER_DEBUG_HEADERS` = comma-separated list of …
> Add temporary debugging code to dump http headers on specific requests

- api/dataset.go
- features/get-dataset-json.feature
- features/get-dataset-observations.feature
Added a check on the /json endpoint to reduce the number of results returned to protect dp-api-router.  The /census-observations endpoint already works in the same way.  This should not affect user experience as users requesting the large datasets are currently receiving 50x status code responses as the api-router cannot process the response.
Ensure the tests pass and the changes make sense.
Anyone
> Fix for oom kill

- api/filter_dimensions.go
- features/filter_dimension.authorised.feature
Add missing header for `/filters/{id}/dimensions/{dimension}`
As done for the following endpoints here -
https://github.com/ONSdigital/dp-cantabular-filter-flex-api/blob/develop/api/filters.go#L466
https://github.com/ONSdigital/dp-cantabular-filter-flex-api/blob/develop/api/filter_dimensions.go#L394
https://github.com/ONSdigital/dp-cantabular-filter-flex-api/blob/develop/api/filter_dimension_options.go#L291
https://github.com/ONSdigital/dp-cantabular-filter-flex-api/blob/develop/api/filter_outputs.go#L17 
Confirm the above has been done, tests pass
Anyone
> add missing header for /filters/{id}/dimensions/{dimension}
