Dockerfile.local, Makefile, features/compose/dp-cantabular-filter-flex-api.yml, features/helloworld.feature, go.mod, go.sum
Add compiler '-race' check flag to component tests
Visually inspect changes.
Anyone.
=> Add race check to component tests

api/filters.go, api/mock/create_filter.request.develop.json, api/mock/create_filter.request.json, service/service.go, service/service_test.go
- Added more logData for errors
- Update and added mock request body for manual testing
- Add Zebedee health check
Anyone
=> update logData and mock requests, add zebedee hc

swagger.yaml
Amending the dimension options response to fit with required standards.
Check the changes match what is required.
Anyone.
=> Updating get dimension options response

api/mock/create_filter.request.develop.json
Update mock POST request body (develop) to have correct dimension names
Anyone
=> update mock post body

api/contract.go, api/contract_test.go
Removed check for a dimension to have a dimension_url field
Read, accept lack of tests, move on
@ChrysmOre
=> Removes the requirement for dimension url when adding a filter

features/steps/component.go
Ensure that we don't send the interrupt signal to the service twice (as it's a blocking message and will hang)
Read, think
gophers other than @goofballLogic
=> fix bug shutting down bdd component

swagger.yaml
Added a new PUT filters/{id} endpoint as it was missing from the original spec.
Ensure the changes make sense.
Anyone.
=> Adding PUT filters endpoint

swagger.yaml
Adding /query endpoint back in as this is to be used to trigger the creation of the download files.
Ensure the changes make sense.
Anyone.
=> Re-adding query endpoint

swagger.yaml
Adding PUT filters/{id}/dimensions/{name} to swagger spec to enable the update of dimensions for a filter.
Ensure the changes make sense.
Anyone.
=> Adding PUT filters/{id}/dimensions/{name} to swagger spec

README.md
Added small change to readme to kick off previously failed build due to GPG issues, from UI merge
No need
Anyone
=> style: line break

features/compose/.env, features/compose/dp-cantabular-filter-flex-api.yml, features/steps/steps.go
Remove some local debug changes
Check makes sense, tests pass
Anyone
=> Undo changes made for local testing

swagger.yaml
Updated the swagger spec to represent the new contracts for endpoints throughout
Check changes make sense and are correct
Anyone
=> update swagger spec throughout

api/api.go, api/contract.go, api/error.go, api/filters.go, api/interface.go, api/mock/cantabular_client.go, datastore/mongodb/error.go, datastore/mongodb/filter_dimensions.go, errors/callback.go, errors/interface.go, features/mock/cantabular_client.go, features/put_filters_dimensions.feature, features/steps/component.go, features/steps/steps.go, service/interface.go, service/mock/datastore.go
Adds a new endpoint enabling the update of a dimension on a filter.
Resolves: [5623](https://trello.com/c/vUgHxQLq)
Confirm the changes match the API spec.
Anyone.
=> Add PUT dimensions output endpoint (Ticket #5623)

api/contract.go, api/filters.go, event/export_start.go, features/steps/steps.go, features/submit_filter.feature, schema/schema.go
- Updated Submit Filter endpoint to return and forward FilterOutputID instead of FilterID
- Couple of small tidy-up changes
Check changes make sense, tests pass
Anyone
=> update submitFilterResponse and exportStart event

service/service.go, service/service_test.go
Added Kafka Producer HealthCheck to the set of health checks. 
Amended unit tests to reflect the extra healthchecker. 
run `make test`
Anyone
=> feat: register Kafka consumer for healthcheck

go.mod, go.sum
Bump `dp-mongodb` to latest version. This removes the need to override the mongo driver transitive dependency
Sense check. Audit pass
Anyone
=> Bump dp-mongodb

main.go
Reverted an unintentional change
Anyone
=> revert an unintentional change

api/filters.go
Forced an empty options slice to be an empty slice rather than nil to prevent it being represented as NULL in mongo.
Anyone
=> prevent options from being null when creating new filter

api/filter_dimension_options.go
Added population type to request to validate dimension options in POST filters/dimensions/option
Anyone
=> add population type to dimension options verification request

api/api.go, api/contract.go, api/filter_dimension_options.go, api/interface.go, datastore/mongodb/filter_dimensions.go, features/compose/deps.yml, features/filter_dimension_options.feature, features/steps/component.go, service/interface.go, service/mock/datastore.go
Added DELETE /filters/{id}/dimensions/{dimension}/options/option
Removes a dimension option from a dimension on a filter
Check changes make sense, tests pass
Anyone
=> Add DELETE /filters/{id}/dimensions/{dim}/options/{option}

api/filters.go
Fix to use return value from getFilterVariable as it presently attempts an additional lookup using the wrong value.
Anyone
=> Use correct dimensionID in filter

api/filters.go, datastore/mongodb/filter_dimensions.go, features/create_filter.feature, go.sum
On Sandbox we were seeing a dereference error around IsBasedOn, whenever
we were trying to change the area types, which would try and create a
new filter.
Sense check it and ensure tests are :green_circle: 
Any ONS developer
=> Check if IsBasedOn is 'nil'

api/contract.go, features/filter_dimension.feature
filter_by_parent was missing in the return when dimension options were queried for 
- Check all test pass
- Code looks reasonable 
Anyone from team b
=> Fixed missing filter_by_parent in dimension item

go.mod, go.sum
Bump dp-component-test library to pick up fix to ErrorFeature
review change and ensure tests are passing
Anyone
=> Bump dp-component-test library to pick up fix to ErrorFeature

api/contract.go, api/contract_test.go, api/filter_dimensions.go, api/filters.go, datastore/mongodb/filter_dimensions.go, features/create_filter.feature, features/filter_dimension.authorised.feature, features/filter_dimension.feature, features/put_filters_dimensions.feature, features/steps/component.go, model/filter.go
Added checks for anywhere a dimension is being added or updated to require `is_area_type` to always be present.
Tidied up some error responses.
Anyone
=> Feature/require is area type field.2

api/contract.go, features/create_filter.feature
Removed the check that is crashing the creation of filter from florence
All tests are green
Anyone
=> Temporary change to fix when IsAreaType is passes as nil from florence

go.mod, go.sum
Bump mongoDB library version, to pick up latest improvements in 'read concern' settings
Review changes
Anyone
=> Bump mongoDB version

datastore/mongodb/filter_outputs.go
Amend query to get filter output to use _id rather than id
Trello - https://trello.com/c/AVljx1Bj/5888-amend-query-in-cantabular-filter-flex-api-to-get-filter-output-to-use-id-rather-than-id
Confirm changes match requested changes in trello ticket
Anyone
=> Amend query to get filter output to use _id rather than id

api/validation.go, features/create_filter.authorized.feature, features/create_filter.feature
Use Geography dimension as first instead of last when recreating dimensions list, as Cantabular requires Geography dimension first for GraphQL queries
Anyone
=> always place geography dimension as first in list for graphql queries

api/api.go
Temporarily removed auth to test the feature
Describe the steps required to test the changes.
Anyone
=> testing if removing auth works

api/api.go
Reintroduced reverted changes
All tests are green
Anyone
=> Reintroduced auth for filter_outputs

api/api.go
Removed auth for **/filter-outputs/{id}** endpoint
All test pass
Anyone
=> removed auth

api/contract.go, api/contract_test.go, features/create_filter.authorized.feature, features/create_filter.feature, features/filter_dimension_options.feature, features/get_filter.feature, features/get_filter_output.feature, features/multivariate_create_filter_authorized.feature, features/put_filter.feature, features/put_filter_output.feature, features/put_filters_dimensions.feature, features/submit_filter.feature, model/filter.go
Add `lowest_geogrpahy` to `Dataset` model
Trello - https://trello.com/c/lmWyoTS6/5923-add-lowestgeography-to-filterdataset-model-in-filter-api-and-filter-flex-api
Confirm changes match those requested in Trello ticket
Anyone
=> add lowest_geography to dataset model

api/contract.go, api/contract_test.go, datastore/mongodb/filter_dimensions.go, features/create_filter.feature, features/delete-filter-dimension-multivariant.feature, features/multivariate_create_filter_authorized.feature
Copy of validation trello ticket 5925
already approved, just sorting out concourse faults through another branch
=> fix: validation from 2 dimensions -> 1

api/contract.go, api/dataset.go, api/dataset_test.go, features/get-dataset-json.feature
Reinstate ID field. This was removed in error in a previous PR
Confirm ID field has been reinstated
Anyone
=> reinstate ID field

swagger.yaml
Cosmetic changes to ensure the swagger spec displays correctly with any additional information on the developer site.
Ensure the changes make sense.
Anyone.
=> Changes required to ensure spec is correct for developer site

go.mod, go.sum
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
=> feat: update api clients go

api/filters.go, datastore/mongodb/config.go, datastore/mongodb/filters.go, features/create_filter.authorized.feature, features/create_filter.feature, features/delete-filter-dimension-multivariant.feature, features/delete-filter-dimension-options.authorized.feature, features/delete-filter-dimension-options.feature, features/filter_dimension.authorised.feature, features/filter_dimension.feature, features/filter_dimension_options.feature, features/get_dimension_options.feature, features/get_filter.feature, features/multivariate_add_dimension.authorized.feature, features/multivariate_create_filter_authorized.feature, features/multivariate_put_dimension.authorized.feature, features/put_filter.feature, features/put_filters_dimensions.feature, features/steps/mongofeature.go, features/submit_filter.feature, service/initialise.go
Update link generation in new filter to use FilterAPIURL and existing link in Version document
Anyone
=> use filterAPIURL and existing Version URL for new filter links

datastore/mongodb/filter_outputs.go, features/put_filter_output.feature, model/filter_output.go
Add xlsx to filterOutputs and allow for in UpdateFilterOutput
Anyone
=> add xlsx to filter-outputs and allow updating in PutFilterOutput

api/contract.go, features/filter_dimension.authorised.feature, features/filter_dimension.feature, features/multivariate_add_dimension.authorized.feature, features/multivariate_put_dimension.authorized.feature, features/put_filters_dimensions.feature
Add default categorisation flag to filter flex api 
ammend tests to include default categorisation to all dimension responses
=> patch: add default categorisation to response

api/dataset.go, features/get-dataset-json.feature, go.mod, go.sum, model/filter.go
Ticket: https://trello.com/c/ytJeJqaw/5978-add-label-to-options-property-in-json-response
Added new field 'lable' to response 
All test are :green_circle: 
And response has label in it
Anyone
=> Added label to json response

api/contract.go, api/filters.go, features/create_filter.authorized.feature, features/create_filter.feature, features/filter_dimension_options.feature, features/get_filter.feature, features/get_filter_output.feature, features/multivariate_add_dimension.authorized.feature, features/multivariate_create_filter_authorized.feature, features/put_filter.feature, features/put_filter_output.feature, features/put_filters_dimensions.feature, features/submit_filter.feature, go.mod, go.sum, model/filter.go, model/filter_output.go
Added 'custom' flag to filter models
Anyone
=> add custom flag to filter models

api/api.go, features/create_custom_filter.feature
Updated the endpoint from` /filters/custom` to `custom/filters`
All test are :green_circle: 
Anyone
=> Updated the endpoint

api/contract.go, api/filter_dimensions.go, features/filter_dimension.authorised.feature, features/filter_dimension.feature, features/filter_dimension_options.feature, features/multivariate_add_dimension.authorized.feature, features/multivariate_put_dimension.authorized.feature, features/put_filters_dimensions.feature
Added IsAreaType to dimension structure so that this is available in every dimension result
- A check of will this break any existing flows
- All check are :green_circle: 
Anyone
=> Added IsAreaType to dimension structure

api/contract.go, api/dataset.go, features/get-dataset-json.feature, features/mock/population.go, go.mod, go.sum
Return count of blocked areas from /json endpoint
Trello - https://trello.com/c/yvpwYpDy/6067-return-count-of-blocked-areas-from-json-endpoint
Confirm changes match the requested changes in Trello ticket
Anyone
=> return count of blocked areas from /json endpoint

api/contract.go, api/dataset.go, features/get-dataset-observations.feature
Ticket: https://trello.com/c/mmfZAyce/6085-implement-blocked-area-count-in-census-observations-cantabular-filter-flex-api
Added rules count to observations response
All test are :green_circle: 
Anyone
=> Added rules count to observations response

features/get-dataset-json.feature, features/get-dataset-observations.feature, go.mod, go.sum
Increased api-clients-go version to remove SDC response from static dataset query.
Ensure the tests pass and the changes make sense.
Anyone.
=> Increasing api-clients-go version to test performance fix

features/get-dataset-json.feature, features/get-dataset-observations.feature, go.mod, go.sum
Reinstating SDC messaging for api queries.
Ensure the tests pass and the changes make sense.
Anyone.
=> Upgrading api-clients-go version to latest version to include SDC

ci/build.yml, ci/lint.yml, ci/unit.yml, go.mod, go.sum
Upgrading dp-kafka version to ensure correct healthcheck status is returned.
Updating go version.
Ensure the changes make sense and the tests pass.
Anyone.
=> Updating dp-kafka version

README.md, config/config.go, config/config_test.go, main.go
Adds a Batch Timeout environment variable and configures OpenTelemetry to use it.
=> DIS-146 OpenTelemetry Batch Timeout

api/dataset.go
Revert temporary debugging code that was added to help with api-router refactoring
Ensure only temp code reverted and tests pass
Anyone
=> Revert temporary debugging code

api/dataset.go
Release branch containing…
- Revert temporary debugging code
Ensure only expected commits and tests pass.
Anyone
=> Release 1.27.0

api/filters.go
Added logging for X-Forwarded headers for debugging in sandbox
Check changes are ok
Anyone
=> added logging for forwraded headers

README.md
Update config values (`ENABLE_URL_REWRITING` &  `CANTABULAR_FILTER_FLEX_API_URL`) for readme file
Confirm changes make sense
Anyone
=> update config readme

Dockerfile.concourse
As per title
Check updated image name with whats in CI elastic container registry.
Fran's team.
=> update Dockerfile.concourse to use ubuntu22.04 image
